Revert "bump dependencies"
This reverts commit e70f1dfb4213a1415f1307175241e57a06226fae.

Somehow material 3 is crashing with the update inside the settings screen (due to the TextField):

```
 FATAL EXCEPTION: main
                                                                                                    Process: de.bixilon.unithen.debug, PID: 19549
                                                                                                    java.util.NoSuchElementException: Collection contains no element matching the predicate.
                                                                                                    	at androidx.compose.ui.util.ListUtilsKt.throwNoSuchElementException(ListUtils.kt:615)
                                                                                                    	at androidx.compose.material3.TextFieldMeasurePolicy.measure-3p2s80s(TextField.kt:1753)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:130)
                                                                                                    	at androidx.compose.ui.node.MeasurePassDelegate.performMeasureBlock$lambda$0(MeasurePassDelegate.kt:173)
...
```